# Generated by Django 5.2.4 on 2025-08-28 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaCompraVenta',
            fields=[
                ('clienteNombre', models.CharField(max_length=25)),
                ('ventaId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ventaCantidad', models.IntegerField()),
                ('productoNombre', models.CharField(max_length=25)),
                ('productoPrecioUnidad', models.IntegerField()),
            ],
            options={
                'db_table': 'compraventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaIngresoInfo',
            fields=[
                ('ingresoId', models.IntegerField(primary_key=True, serialize=False)),
                ('ingresoValor', models.IntegerField()),
                ('ingresoCantidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('usuNombre', models.CharField(max_length=25)),
                ('usuApellido', models.CharField(max_length=25)),
                ('usuCorreo', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'ingresoinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaProcesoIngreso',
            fields=[
                ('usuNombre', models.CharField(max_length=25)),
                ('ingresoId', models.IntegerField(primary_key=True, serialize=False)),
                ('ingresoValor', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'procesoingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteCedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clienteNombre', models.CharField(max_length=25, unique=True)),
                ('clienteApellido', models.CharField(max_length=25)),
                ('clienteUsuario', models.CharField(max_length=10)),
                ('clienteContrasena', models.CharField(max_length=10)),
                ('clienteFoto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('clienteCorreo', models.EmailField(max_length=50)),
                ('clienteTelefono', models.CharField(max_length=10)),
                ('clienteDireccion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('ingresoId', models.AutoField(primary_key=True, serialize=False)),
                ('ingresoValor', models.IntegerField()),
                ('ingresoCantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('proveedorNit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolId', models.AutoField(primary_key=True, serialize=False)),
                ('rolNombre', models.CharField(max_length=20)),
                ('rolDescripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productoNombre', models.CharField(max_length=25)),
                ('productoPrecioUnidad', models.IntegerField()),
                ('productoCantidad', models.IntegerField()),
                ('productoDescripcion', models.CharField(max_length=225)),
                ('ingreso', models.ForeignKey(db_column='ingresoId', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.ingreso')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='proveedorNit',
            field=models.ForeignKey(db_column='proveedorNit', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.proveedor'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuCedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuUsuario', models.CharField(max_length=10)),
                ('usuNombre', models.CharField(max_length=25, unique=True)),
                ('usuApellido', models.CharField(max_length=25)),
                ('usuContrasena', models.CharField(max_length=10)),
                ('usuCorreo', models.EmailField(max_length=35)),
                ('usuTelefono', models.CharField(max_length=10)),
                ('usuDireccion', models.CharField(max_length=30)),
                ('usuFoto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuCedula',
            field=models.ForeignKey(db_column='usuCedula', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.usuario'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipoId', models.AutoField(primary_key=True, serialize=False)),
                ('equipoRef', models.CharField(max_length=30)),
                ('equipoNovedad', models.CharField(max_length=300)),
                ('equipoFecha', models.DateField(auto_now_add=True)),
                ('equipoEstado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('clienteNombre', models.ForeignKey(db_column='clienteNombre', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.cliente', to_field='clienteNombre')),
                ('usuNombre', models.ForeignKey(db_column='usuNombre', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.usuario', to_field='usuNombre')),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ventaCantidad', models.IntegerField()),
                ('ventaTipoProducto', models.CharField(blank=True, max_length=20, null=True)),
                ('ventaMetodoPago', models.CharField(max_length=20)),
                ('ventaPrecio', models.IntegerField()),
                ('clienteCedula', models.ForeignKey(db_column='clienteCedula', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.cliente')),
                ('productoId', models.ForeignKey(db_column='productoId', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.producto')),
                ('usuCedula', models.ForeignKey(db_column='usuCedula', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.usuario')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
