# Generated by Django 5.1.6 on 2025-09-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rolId',
            field=models.ForeignKey(db_column='rolId', default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.rol'),
        ),
    ]
