# Generated by Django 5.2.2 on 2025-06-10 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('ingresoId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ingresoValor', models.IntegerField()),
                ('ingresoCantidad', models.IntegerField()),
                ('proveedor', models.ForeignKey(db_column='proveedor_nit', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.proveedor')),
            ],
            options={
                'db_table': 'ingreso',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productoNombre', models.CharField(max_length=25)),
                ('productoPrecioUnidad', models.IntegerField()),
                ('productoCantidad', models.IntegerField()),
                ('productoDescripcion', models.CharField(max_length=225)),
                ('ingreso', models.ForeignKey(db_column='ingresoId', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.ingreso')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuCedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuUsuario', models.CharField(max_length=10)),
                ('usuNombre', models.CharField(max_length=25)),
                ('usuApellido', models.CharField(max_length=25)),
                ('usuContraseña', models.CharField(max_length=10)),
                ('usuCorreo', models.EmailField(max_length=35)),
                ('usuTelefono', models.CharField(max_length=10)),
                ('usuDireccion', models.CharField(max_length=30)),
                ('usuFoto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuCedula',
            field=models.ForeignKey(db_column='usuCedula', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.usuario'),
        ),
    ]
