# Generated by Django 5.2.5 on 2025-09-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0002_usuario_rolid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rolId',
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoPrecioUnidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
