# Generated by Django 5.2.6 on 2025-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0002_usuario_rolid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rolId',
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoPrecioUnidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
