# Generated by Django 5.2.3 on 2025-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0002_remove_proveedor_id_alter_proveedor_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='ingresoId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
