# Generated by Django 5.2.3 on 2025-06-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0004_alter_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolId', models.AutoField(primary_key=True, serialize=False)),
                ('rolNombre', models.CharField(max_length=20)),
                ('rolDescripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuContraseña',
            new_name='usuContrasena',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteCedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('clienteNombre', models.CharField(max_length=25)),
                ('clienteApellido', models.CharField(max_length=25)),
                ('clienteUsuario', models.CharField(max_length=10)),
                ('clienteContrasena', models.CharField(max_length=10)),
                ('clienteFoto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('clienteCorreo', models.EmailField(max_length=50)),
                ('clienteTelefono', models.CharField(max_length=10)),
                ('clienteDireccion', models.CharField(max_length=40)),
                ('rolId', models.ForeignKey(db_column='rolId', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.rol')),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ventaCantidad', models.IntegerField()),
                ('ventaTipoProducto', models.CharField(max_length=20)),
                ('ventaMetodoPago', models.CharField(max_length=20)),
                ('ventaPrecio', models.IntegerField()),
                ('clienteCedula', models.ForeignKey(db_column='clienteCedula', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.cliente')),
                ('productoId', models.ForeignKey(db_column='productoId', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.producto')),
                ('usuCedula', models.ForeignKey(db_column='usuCedula', on_delete=django.db.models.deletion.CASCADE, to='proveedor_app.usuario')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
