# Generated by Django 5.2.3 on 2025-06-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor_app', '0005_rol_rename_usucontraseña_usuario_usucontrasena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rolId',
        ),
    ]
